using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
// __ equals "-" _ equal" " 
namespace CallYourShot.Models.Enums
{
    public enum GamingConsoles
    {
        _3DO,
        Arcade,
        Atari_2600,
        Atari_5200,
        Atari_7800,
        Atari_Jaguar,
        Atari_Lynx,
        ColecoVision,
        Commodore_64,
        Commodore_Amiga,
        Famicom,
        Game_Boy,
        Game_Boy_Advance,
        Google_Stadia,
        Intellivision,
        Magnavox_Odyssey,
        Mobile_Devices,
        N__Gage,
        Neo_Geo,
        Nintendo_3DS,
        Nintendo_64,
        Nintendo_DS,
        Nintendo_Entertainment_System,
        Nintendo_GameCube,
        Nintendo_Switch,
        Oculus_Quest,
        Oculus_Rift,
        PC,
        PlayStation,
        PlayStation_2,
        PlayStation_3,
        PlayStation_4,
        PlayStation_5,
        PlayStation_Portable,
        PlayStation_Vita,
        Sega_32x,
        Sega_CD,
        Sega_Dreamcast,
        Sega_Game_Gear,
        Sega_Genesis,
        Sega_Master_System,
        Sega_Saturn,
        Super_Famicom,
        Super_Nintendo_Entertainment_System,
        TurboGrafx__16,
        VIC__20,
        Wii,
        Wii_U,
        Xbox,
        Xbox_360,
        Xbox_One,
        Xbox_Series_X,
        ZX_Spectrum,
    }
}
